### ISSUE TITLE
LinkTracking needs null check for empty <a>

### ISSUE THREAD

**Issue by nicholaszuccarelli** [juhasev/laravel-ses#17]
MailProcessor line 98.
If a supplied `<a>` in the email contents does not have a href (`<a>Empty Link</a>`), it will throw an error when attempting to perform link tracking on the email contents.

![image](https://user-images.githubusercontent.com/13761766/206049217-906e1c2c-3f61-4287-a51b-d3fda3bc7aca.png)

"Argument 1 passed to Juhasev\LaravelSes\MailProcessor::createAppLink() must be of type string, null given).
Simply need an if statement.
```
if ($originalUrl) {
$anchor->setAttribute(...)
}
```

**Comment by leMaur** [comment]
Thanks @nicholaszuccarelli for pointing that out!

**Comment by nicholaszuccarelli** [comment]
Thanks for the speedy response! :)
