### ISSUE TITLE
email links: change from varchar to text for original_url

### ISSUE THREAD

**Issue by nicholaszuccarelli** [juhasev/laravel-ses#22]
the laravel_ses_email_links table needs the `original_url` column changed from `varchar` to `text`.
There have been cases where I send out signed s3 URLs to my users and these URLs can be over 500 characters long.
Currently the link is being concat to the varchar(191) limit so the link they receive is invalid.

**Comment by juhasev** [comment]
Do you want to submit a PR? I am happy to merge that in.

**Comment by nicholaszuccarelli** [comment]
Pull request created
