### ISSUE TITLE
[Question] Is it working with Laravel Notifications?

### ISSUE THREAD

**Issue by Jubeki** [juhasev/laravel-ses#4]
In the examples is only `SesMail` used. Can I work with Notifications too?
https://laravel.com/docs/7.x/notifications#introduction

Do I need to setup another MailDriver for this to be working?
Like register an SesMail in the `mail/config.php`?

**Comment by juhasev** [comment]
No this package is hard coded to receive notifications from AWS SES. Notification sent to SMS would not generate call backs like AWS SES.
