### ISSUE TITLE
Laravel 8

### ISSUE THREAD

**Issue by piep14** [juhasev/laravel-ses#6]
Hi

Great package ! 

Can be possible to update to use it on laravel 8 ?

Thank you so much!!!

**Comment by juhasev** [comment]
Planning on updating it next week as we migrate our entire project to Laravel 8. Feel free to create a PR if you want to contribute. Should be as simple as rolling up the laravel version and making sure unit tests still pass.

**Comment by piep14** [comment]
Hello @juhasev 

I saw that you have updated your package. However, the update is not working. Here are the errors reported: 

```Problem 1
    - Installation request for juhasev/laravel-ses ^1.1 -> satisfiable by juhasev/laravel-ses[v1.1.0, v1.1.1, v1.1.2, v1.1.3].
    - Can only install one of: guzzlehttp/guzzle[7.3.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.3.0].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.3.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.3.0].```

**Comment by juhasev** [comment]
Try removing your guzzle dependency in your local project. It seems like your project is loading a outdated guzzle package. This package is bundled with Laravel so I recommend you change you references to do

``` use Illuminate\Support\Facades\Http;```

See the details. This only works on Laravel 7+. 

See https://laravel.com/docs/8.x/http-client

**Comment by juhasev** [comment]
Can you post your composer.json? If you are on Laravel 8 try the dev-master branch. In your composer.json use

"juhasev/laravel-ses": "dev-master"

I have not yet published a tag for Laravel 8
