### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by soundar8562** [juhasev/laravel-ses#7]
Problem 1
    - juhasev/laravel-ses[v1.1.0, ..., v1.1.3] require illuminate/support 7.* -> found illuminate/support[v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires juhasev/laravel-ses ^1.1 -> satisfiable by juhasev/laravel-ses[v1.1.0, v1.1.1, v1.1.2, v1.1.3].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

![image](https://user-images.githubusercontent.com/54890548/114862746-87331480-9e0c-11eb-8e6d-4fb72a214182.png)

Can you help me to sort this out?

**Comment by juhasev** [comment]
Can you post your composer.json? If you are on Laravel 8 try the dev-master branch. In your composer.json use

"juhasev/laravel-ses": "dev-master"

I have not yet published a tag for Laravel 8
