### ISSUE TITLE
Laravel 6.x ?

### ISSUE THREAD

**Issue by rxng** [juhasev/laravel-ses#9]
Hey there, the repo mentioned that Laravel 6.x is supported, but composer require juhasev/laravel-ses:* on Laravel version 6.20 returns "no matches found: juhasev/laravel-ses:*".

Can you confirm whether 6.x support is still available and how to get it ? Thank you!

**Comment by juhasev** [comment]
There was some mailer update between Laravel 6 and 7. See version [v0.8.4](https://github.com/juhasev/laravel-ses/releases/tag/v0.8.4). That is the last version that supports Laravel 6.x.
